create table if not exists public.contatos (
  id bigint generated by default as identity primary key,
  nome text not null,
  email text not null,
  telefone text,
  servico text not null,
  mensagem text,
  consentimento boolean not null default false,
  consentido_em timestamptz not null default now(),
  criado_em timestamptz not null default now(),
  constraint contatos_consentimento_check check (consentimento = true)
);

alter table public.contatos enable row level security;

create policy "Permitir cadastro de contato com consentimento"
  on public.contatos
  for insert
  to anon
  with check (consentimento = true);
